config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :customers
  resources :provinces
  resources :categories
  resources :products
  resources :orders
  resources :product_categories
  resources :order_products

  post    'add_to_cart/:id',          to: "products#add_to_cart",         as: "add_to_cart"
  delete  'remove_from_cart/:id',     to: "products#remove_from_cart",    as: "remove_from_cart"
  delete  'decrement_from_cart/:id',  to: "products#decrement_from_cart", as: "decrement_from_cart"
  get     'clear_cart',               to: "products#clear_cart",          as: "clear_cart"

  get     "login",  to: "customers#login",        as: "show_login_form"
  post    "login",  to: "customers#authenticate", as:"authenticate"
  delete  "logout", to: "customers#logout",       as:"logout"

  get "checkout", to: "checkout#index", as: "checkout"
  get "thankyou", to: "checkout#thankyou"

  get "invoice", to: "orders#invoice", as: "invoice"

  get "about", to: "products#about", as: "about"
  get "specials", to: "products#specials", as: "specials"

end


  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController
  before_action :initialize_session
  before_action :load_cart_variable
  before_action :get_customer
  before_action :calculate_taxes

  def index
  end

  def thankyou
    @order = Order.last
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  private
    def initialize_session
      session[:cart] ||= Hash.new
    end

    def load_cart_variable
      @cart_contents = Product.find(session[:cart].keys)
      @cart_subtotal = 0

      session[:cart].each do |prod_id,qty|
        price = Product.find(prod_id.to_i).price
        @cart_subtotal += (price*qty)/100.0
      end
    end

    def get_customer
      @customer = Customer.find_by(id: session[:customer_id])
    end

    def calculate_taxes
      # @customer = Customer.find_by(id: session[:customer_id])
      unless @customer.nil?
        @taxes = {  "GST" => @customer.province.GST,
                    "PST" => @customer.province.PST,
                    "HST" => @customer.province.HST
                  }
        @GST_due = (@customer.province.GST)*(@cart_subtotal)/100.0
        @PST_due = (@customer.province.PST)*(@cart_subtotal)/100.0
        @HST_due = (@customer.province.HST)*(@cart_subtotal)/100.0

        @total_tax_amount = @GST_due + @PST_due + @HST_due
        @cart_grandtotal = (@cart_subtotal + @total_tax_amount)
      end
    end
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/views/checkout/_show_taxes.html.erb
<% unless @customer.province.GST == 0 %>
  <tr>
    <td></td>
    <td></td>
    <td><strong class="title is-6">GST:</strong></td>
    <td><%= number_to_currency @GST_due %></td>
    <td></td>
  </tr>
<% end %>
<% unless @customer.province.PST == 0 %>
  <tr>
    <td></td>
    <td></td>
    <td><strong class="title is-6">PST:</strong></td>
    <td><%= number_to_currency @PST_due %></td>
    <td></td>
  </tr>
<% end %>
<% unless @customer.province.HST == 0 %>
  <tr>
    <td></td>
    <td></td>
    <td><strong class="title is-6">HST:</strong></td>
    <td><%= number_to_currency @HST_due %></td>
    <td></td>
  </tr>
<% end %>
  <tr>
  <td></td>
  <td></td>
  <td><strong class="title is-6">Grand Total:</strong></td>
  <td><%= number_to_currency @cart_grandtotal %></td>
  </tr>

app/views/checkout/index.html.erb
<h3 class="title is-4">Checkout</h3>

<% unless session[:customer_id].blank? || session[:customer_id].nil?  %>
  <div class="mb-3">
    <h2 class="title is-6 mb-0">Confirm Shipping Address:</h2>
    <p class="has-text-weight-bold"><%= @customer.name%></p>
    <p><%= @customer.address%></p>
    <p><%= @customer.province.name%></p>
    <p class="mt-2 mb-3">Not your address? <%= link_to "Update Address", edit_customer_path(@customer) %></p>
  </div>

  <%# cart contents %>
  <%= render "products/cart_contents", show_taxes: true %>


  <div class="block is-flex">
    <%= link_to "Place Order", invoice_path, class:"button mr-4 is-success is-light is-outlined" %></p>
    <%#= link_to "Create New Order", new_order_path, class:"button mr-4 is-success is-light is-outlined" %></p>
    <%= link_to "Clear Cart", clear_cart_path, class:"button is-danger is-light is-outlined" %></p>
  </div>
<% else %>
  <div class="block">
    <p>Already have an account? <%= link_to "Log In", show_login_form_path %></p>
    <p><%= link_to "Sign Up", new_customer_path %> to save your shipping information.</p>
  </div>
<% end %>

app/views/checkout/thankyou.html.erb
<h3 class="title is-4">Thank you for your order!</h3>

<p>Your goodies are on the way.</p>

<%# cart contents %>
<%# <%= render "products/cart_contents", show_taxes: true > %>
<%#= @order.inspect %>

<table class="table is-striped my-4">
  <thead>
    <th></th>
    <th>Product</th>
    <th>Quantity</th>
  </thead>

  <% @order_products.each do |op| %>
    <tr>
      <td>
        <% if op.product.image.present? %>
          <%= image_tag op.product.image, size: 50 %>
        <% end %>
      </td>
      <td><%= op.product.name %></td>
      <td class="has-text-centered"><%= op.qty %></td>
    </tr>
  <% end %>

</table>