config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :customers
  resources :provinces
  resources :categories
  resources :products
  resources :orders
  resources :product_categories
  resources :order_products

  post    'add_to_cart/:id',          to: "products#add_to_cart",         as: "add_to_cart"
  delete  'remove_from_cart/:id',     to: "products#remove_from_cart",    as: "remove_from_cart"
  delete  'decrement_from_cart/:id',  to: "products#decrement_from_cart", as: "decrement_from_cart"
  get     'clear_cart',               to: "products#clear_cart",          as: "clear_cart"

  get     "login",  to: "customers#login",        as: "show_login_form"
  post    "login",  to: "customers#authenticate", as:"authenticate"
  delete  "logout", to: "customers#logout",       as:"logout"

  get "checkout", to: "checkout#index", as: "checkout"
  get "thankyou", to: "checkout#thankyou"

  get "invoice", to: "orders#invoice", as: "invoice"

  get "about", to: "products#about", as: "about"
  get "specials", to: "products#specials", as: "specials"

end


  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

app/models/order.rb
class Order < ApplicationRecord
  # associations
  belongs_to :customer
  has_many :order_products, dependent: :destroy
  has_many :products, through: :order_products
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: %i[ show edit update destroy ]
  before_action :load_cart_variable
  before_action :get_customer
  before_action :calculate_taxes

  def invoice
    @customer = Customer.find(session[:customer_id])

    # generate a new order entry
    @order = Order.new(
      customer_id: @customer.id,
      payment_id: rand(111111..999999),
      status: "Pending",
      GST: @customer.province.GST,
      PST: @customer.province.PST,
      HST: @customer.province.HST
    )

    # loop through all the cart items and genereate OrderProduct entries
    if @order.save
      session[:cart].each do | prod_id, qty |
        new_order_prod = OrderProduct.new(
          order_id: @order.id,
          product_id: prod_id,
          qty: qty,
          price: Product.find(prod_id.to_i).price
        )
        new_order_prod.save

        # save the cart in picklist
        # @picklist = session[:cart].clone

        # get the products in the cart
        # @picklist_products = Product.find(@picklist.keys)

        # empty the cart
        session[:cart] = nil
      end

      redirect_to thankyou_path
    else
      redirect_to root_path, notice: "CANNOT SAVE ORDER."
    end

  end

  # GET /orders or /orders.json
  def index
    @orders = Order.all.reverse
  end

  # GET /orders/1 or /orders/1.json
  def show
    @order_products = OrderProduct.where(order_id: @order.id)
  end

  # GET /orders/new
  def new
    @order = Order.new
    @province = Province.all
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders or /orders.json
  def create
    # create new order with the params in the form
    @order = Order.new(order_params)

    # loop through the cart items and save to OrderProducts
    if @order.save
      session[:cart].each do | prod_id, qty |
        new_order_prod = OrderProduct.new(
          order_id: @order.id,
          product_id: prod_id,
          qty: qty,
          price: Product.find(prod_id.to_i).price
        )
      new_order_prod.save
      end

      # empty the cart
      session[:cart] = nil
      redirect_to order_url(@order), notice: "Order was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /orders/1 or /orders/1.json
  def update
    if @order.update(order_params)
      redirect_to orders_path, notice: "Order was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /orders/1 or /orders/1.json
  def destroy
    @order.destroy

    redirect_to orders_path, notice: "Order was successfully destroyed."
    head :no_content
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def order_params
      params.require(:order).permit(:customer_id, :payment_id, :status, :GST, :PST, :HST)
    end

    def initialize_session
      session[:cart] ||= Hash.new
    end

    def load_cart_variable
      unless session[:cart].blank?
        @cart = session[:cart]
        @cart_contents = Product.find(session[:cart].keys)
        @cart_subtotal = 0

        session[:cart].each do |prod_id,qty|
          price = Product.find(prod_id.to_i).price
          @cart_subtotal += (price*qty)/100.0
        end

      end
    end

    def get_customer
      @customer = Customer.find_by(id: session[:customer_id])
    end

    def calculate_taxes
      # @customer = Customer.find_by(id: session[:customer_id])
      unless @customer.nil? || session[:cart].blank?
        @taxes = {  "GST" => @customer.province.GST,
                    "PST" => @customer.province.PST,
                    "HST" => @customer.province.HST
                  }
        @GST_due = (@customer.province.GST)*(@cart_subtotal)/100.0
        @PST_due = (@customer.province.PST)*(@cart_subtotal)/100.0
        @HST_due = (@customer.province.HST)*(@cart_subtotal)/100.0

        @total_tax_amount = @GST_due + @PST_due + @HST_due
        @cart_grandtotal = (@cart_subtotal + @total_tax_amount)
      end
    end
  end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order) do |form| %>

  <% if order.errors.any? %>
    <div style="color: red">
      <ul>
        <% order.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :customer_id, class:"label" %>
    <div class="select">
    <% if session[:customer_id].nil? %>
      <%= form.select :customer_id, options_from_collection_for_select(Customer.all, 'id', 'name')%>
    <% else %>
      <%= form.select :customer_id, options_from_collection_for_select(Customer.all, 'id', 'name', @customer.id)%>
    <% end %>
    </div>
  </div>

  <div class="mb-3">
    <%= form.label :payment_id, "Payment ID", class:"label" %>
    <%= form.text_field :payment_id, value:rand(111111..999999), class:"input" %>
  </div>

  <div class="mb-3">
    <%= form.label :status, class:"label"  %>
    <div class="select">
      <%= form.select :status, options_for_select(%w[Pending Paid Shipped], "Pending"), prompt:"select status"%>
    </div>
  </div>

  <div class="mb-3">
    <% if session[:customer_id].nil? %>
      <%= form.label :GST, "GST", class:"label" %>
      <%= form.select :GST, options_from_collection_for_select(Province.select(:GST).distinct, 'GST','GST'), prompt: ""%>
    <% else %>
      <%= form.label :GST, "#{@customer.province.name} GST", class:"label" %>
      <%= form.select :GST, options_from_collection_for_select(Province.select(:GST).distinct, 'GST','GST', @customer.province.GST)%>
    <% end %>
  </div>

  <div class="mb-3">
    <% if session[:customer_id].nil? %>
      <%= form.label :PST, "PST", class:"label" %>
      <%= form.select :PST, options_from_collection_for_select(Province.select(:PST).distinct, 'PST','PST'), prompt: ""%>
    <% else %>
      <%= form.label :PST, "#{@customer.province.name} PST", class:"label" %>
      <%= form.select :PST, options_from_collection_for_select(Province.select(:PST).distinct, 'PST','PST', @customer.province.PST)%>
    <% end %>
  </div>

  <div class="mb-3">
    <% if session[:customer_id].nil? %>
      <%= form.label :HST, "HST", class:"label" %>
      <%= form.select :HST, options_from_collection_for_select(Province.select(:HST).distinct, 'HST','HST'), prompt: ""%>
    <% else %>
      <%= form.label :HST, "#{@customer.province.name} HST", class:"label" %>
      <%= form.select :HST, options_from_collection_for_select(Province.select(:HST).distinct, 'HST','HST', @customer.province.HST)%>
    <% end %>
  </div>

  <div>
    <%= form.submit class:"button is-outlined is-light is-success" %>
  </div>
<% end %>

app/views/orders/_order.html.erb
<%= order.inspect %>
<div id="<%= dom_id order %>">
  <p>
    <strong>Customer:</strong>
    <%= link_to order.customer.name, order.customer %>
  </p>

  <p>
    <strong>Payment ID:</strong>
    <%= order.payment_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= order.status %>
  </p>

  <p>
    <strong>GST:</strong>
    <%= order.GST %>
  </p>

  <p>
    <strong>PST:</strong>
    <%= order.PST %>
  </p>

  <p>
    <strong>HST:</strong>
    <%= order.HST %>
  </p>

</div>

app/views/orders/edit.html.erb
<h1 class="title">Edit Order</h1>

<%= render "form", order: @order %>

<br>

<div>
  <%= link_to "Show this order", @order %> |
  <%= link_to "Back to orders", orders_path %>
</div>

app/views/orders/index.html.erb
<div class="is-flex is-flex-direction-column is-align-items-center">
  <p style="color: green"><%= notice %></p>

  <h1 class="title">Orders</h1>

  <%#= link_to "New order", new_order_path, class:"button" %>

  <table class="table is-striped">
  <tr>
    <th>Order ID</th>
    <th>Status</th>
    <th>Transaction Date</th>
    <th>Payment ID</th>
    <th>Customer</th>
    <th>GST</th>
    <th>PST</th>
    <th>HST</th>
    <th></th>
    <th></th>
  </tr>
    <% @orders.each do |o|%>
      <tr>
        <td><%=link_to o.id, order_path(o.id)%></td>
        <td>
          <%= form_with(model: o) do |form| %>
            <div class="select is-small">
              <%= form.select :status, options_for_select(%w[Pending Paid Shipped], "#{o.status}"), prompt:"select status"%>
            </div>
            <%= form.submit "update status" , class:"button is-small is-inline"%>
          <% end %>
        </td>
        <td><%= o.created_at.strftime('%m/%d/%Y %H:%M') %></td>
        <td><%= o.payment_id %></td>
        <td><%= link_to o.customer.name, o.customer %></td>
        <% unless o.GST == 0 %>
          <td class="has-text-centered"><%= number_to_percentage o.GST, precision:0 %></td>
        <% else %>
          <td class="has-text-centered">-</td>
        <% end %>
        <% unless o.PST == 0 %>
          <td class="has-text-centered"><%= number_to_percentage o.PST, precision:0 %></td>
        <% else %>
          <td class="has-text-centered">-</td>
        <% end %>
        <% unless o.HST == 0 %>
          <td class="has-text-centered"><%= number_to_percentage o.HST, precision:0 %></td>
        <% else %>
          <td class="has-text-centered">-</td>
        <% end %>
        <td><%= link_to "EDIT", edit_order_path(o.id) %></td>
        <td><%= link_to "DELETE", order_path(o.id), data: { turbo_method: :delete, turbo_confirm: "Delete?" }, class: "button is-small" %></td>
      </tr>
  <% end %>

  </table>
</div>

app/views/orders/invoice.html.erb
<h3 class="title is-4">Thank you for your order!</h3>

<p>Your goodies are on the way.</p>

<%# cart contents %>
<%# <%= render "products/cart_contents", show_taxes: true > %>


<%= @customer.name%>
<%= @picklist_products.inspect%>


<%= Order.last.inspect %>


   <table class="table is-striped">
      <tr>
        <th></th>
        <th>Item</th>
        <th class="has-text-centered">QTY</th>
        <th class="has-text-centered">Unit Price</th>
        <th></th>
      </tr>
      <% @picklist_products.each do |p|%>
        <tr>
          <td>
            <%# if p.image.present? %>
              <%#= image_tag p.image.variant(resize_to_fit: [50,50]) %>
            <%# end %>
          </td>
          <td>
            <p class="py-2"><%= p.name %></p>
          </td>
          <td class="has-text-centered">
            <p class="px-3"><%= p %></p>
          </td>
          <td>
            <p class="py-2"><%= number_to_currency p.price.to_i/100.0  %></p>
          </td>
          <td></td>
        </tr>
      <% end %>
      <tr class="">
        <td></td>
        <td></td>
        <td><strong class="title is-6">Subtotal:</strong></td>
        <td><%=  %></td>
        <td></td>
      </tr>
  <p class="px-3"><%= @picklist%></p>
        <%#= render "checkout/show_taxes"%>
      <%# end %>
    </table>

app/views/orders/new.html.erb
<h1 class="title">New Order</h1>
<h3 class="title is-4">Order Review</h3>
<%= session[:customer_id] %>
<% unless session[:customer_id].present? %>
  <div class="mb-3">
    <h2 class="title is-6 mb-0">Confirm Shipping Address:</h2>
    <p class="has-text-weight-bold"><%= @customer.name%></p>
    <p><%= @customer.address%></p>
    <p><%= @customer.province.name%></p>
    <p class="mt-2 mb-3">Not your address? <%= link_to "Update Address", edit_customer_path(@customer) %></p>
  </div>
<% else %>
  <div class="block">
    <p>Already have an account? <%= link_to "Log In", show_login_form_path %></p>
    <p><%= link_to "Sign Up", new_customer_path %> to save your shipping information.</p>
  </div>
<% end %>

<%# cart contents %>
<%= render "products/cart_contents", show_taxes: true %>
<%= link_to "Clear Cart", clear_cart_path, class:"button is-danger is-light is-outlined" %></p>


<%= render "form", order: @order %>

app/views/orders/show.html.erb
<p style="color: green"><%= notice %></p>

<%# render @order %>

<div>
  <p>
    <strong>Customer:  </strong>
    <%= link_to @order.customer.name, @order.customer %>
  </p>

  <p>
    <strong>Order ID:  </strong>
    <%= @order.id %>
  </p>

  <p>
    <strong>Payment ID:  </strong>
    <%= @order.payment_id %>
  </p>
  <p>
    <strong>Status:  </strong>
    <%= @order.status %>
  </p>

  <br>

  <p>
    <strong>GST:  </strong>
    <%= @order.GST %>
  </p>

  <p>
    <strong>PST:  </strong>
    <%= @order.PST %>
  </p>

  <p>
    <strong>HST:  </strong>
    <%= @order.HST %>
  </p>

  <br>
</div>

<table class="table is-striped">
  <thead>
    <th>Product</th>
    <th>Quantity</th>
    <th>Unit Price</th>
  </thead>


  <% @order_products.each do |op| %>
    <tr>
      <td><%= op.product.name %></td>
      <td><%= op.qty %></td>
      <td><%= number_to_currency op.price/100.0 %> </td>
    </tr>
  <% end %>

</table>