config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :customers
  resources :provinces
  resources :categories
  resources :products
  resources :orders
  resources :product_categories
  resources :order_products

  post    'add_to_cart/:id',          to: "products#add_to_cart",         as: "add_to_cart"
  delete  'remove_from_cart/:id',     to: "products#remove_from_cart",    as: "remove_from_cart"
  delete  'decrement_from_cart/:id',  to: "products#decrement_from_cart", as: "decrement_from_cart"
  get     'clear_cart',               to: "products#clear_cart",          as: "clear_cart"

  get     "login",  to: "customers#login",        as: "show_login_form"
  post    "login",  to: "customers#authenticate", as:"authenticate"
  delete  "logout", to: "customers#logout",       as:"logout"

  get "checkout", to: "checkout#index", as: "checkout"
  get "thankyou", to: "checkout#thankyou"

  get "invoice", to: "orders#invoice", as: "invoice"

  get "about", to: "products#about", as: "about"
  get "specials", to: "products#specials", as: "specials"

end


  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

app/models/product.rb
class Product < ApplicationRecord
  # associations
  has_many :product_categories
  has_many :categories, through: :product_categories

  # has_many :order_products
  # has_many :orders, through: :order_products

  # validations
  validates :name, presence: true

  # active storage
  has_one_attached :image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]
  before_action :initialize_session #create empty cart array, if not already initialized
  before_action :load_cart_variable

  # GET /products or /products.json
  def index
    @products = Product.all
  end

  # GET /products/1 or /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products or /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to product_url(@product), notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1 or /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to product_url(@product), notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1 or /products/1.json
  def destroy
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end


  def add_to_cart
    prod_key = params[:id] # is of datatype string

    if session[:cart].keys.include?(prod_key)
      session[:cart][prod_key] += 1
    else
      session[:cart][prod_key] = 1
    end

    # prevent rails from trying to load up a view of the same name as the action
    redirect_to products_path
  end

  def remove_from_cart
    prod_key = params[:id]
    session[:cart].delete(prod_key)

    redirect_to products_path
  end

  def decrement_from_cart
    prod_key = params[:id]

    if session[:cart][prod_key] == 1
      session[:cart].delete(prod_key)
    else
      session[:cart][prod_key] -= 1
    end

    redirect_to products_path
  end

  def clear_cart
    session[:cart] = Hash.new
    redirect_to products_path
  end

  private

    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :image)
    end

    def initialize_session
      session[:cart] ||= Hash.new
    end

    def load_cart_variable
      # loads a set of objects from the db
      @cart_contents = Product.find(session[:cart].keys)
      @cart_subtotal = 0

      session[:cart].each do |prod_id,qty|
        price = Product.find(prod_id.to_i).price
        @cart_subtotal += (price*qty)/100.0
      end
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_cart_contents.html.erb
<%# display cart contents %>
<div class="block">
  <% if @cart_contents.empty?%>
    <p class="has-text-centered">No items in cart.</p>
  <% else %>
    <h3 class="title is-6 mb-3 pt-3 has-text-centered">Shopping Cart</h3>
    <table class="table is-striped">
      <tr>
        <th></th>
        <th>Item</th>
        <th class="has-text-centered">QTY</th>
        <th class="has-text-centered">Unit Price</th>
        <th></th>
      </tr>
      <% @cart_contents.each do |p|%>
        <tr>
          <td>
            <% if p.image.present? %>
              <%= image_tag p.image, size: 50 %>
            <% end %>
          </td>
          <td>
            <p class="py-2"><%= p.name %></p>
          </td>
          <td class="has-text-centered">
            <%= render partial: "products/qty_buttons", locals: {product: p} %>
          </td>
          <td>
            <p class="py-2"><%= number_to_currency p.price.to_i/100.0  %></p>
          </td>
          <td>
            <div class="py-2">
              <%= button_to "x", remove_from_cart_path(p.id),class:"button is-small is-danger is-outlined", method: :delete %>
            </div>
          </td>
        </tr>
      <% end %>
      <tr class="">
        <td></td>
        <td></td>
        <td><strong class="title is-6">Subtotal:</strong></td>
        <td><%= number_to_currency @cart_subtotal %></td>
        <td></td>
      </tr>
      <%if show_taxes%>
        <%= render "checkout/show_taxes"%>
      <% end %>
    </table>
  <% end %>
</div>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %>

  <% if product.errors.any? %>
    <div style="color: red">
      <ul>
        <% product.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <p class="title is-4"><%= product.name %></p>
  </div>

  <div class="mb-3">
    <%= form.label :description, class:"label" %>
    <%= form.text_area :description, class:"textarea" %>
  </div>

  <div class="mb-3">
    <%= form.label :price, class:"label" %>
    $<%= form.number_field :price, value: product.price.to_i/100.00 %>
  </div>

  <div class="mb-3">
    <%= form.label :image, class:"label" %>
    <%= form.file_field :image %>
  </div>

  <div class="mb-3">
    <%= form.label :category, "Add Another Category", class:"label" %>
    <div class="select">
      <%= form.select :category, options_from_collection_for_select(Category.all,'id','name'), prompt:"select category"%>
    </div>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/products/_product.html.erb
<div class="column is-3 card mx-5 my-5 py-5 px-5" id="<%# dom_id product %>">

  <%# card title %>
  <% if show_page %>
    <p class="title is-5 has-text-centered mb-3"><%= product.name %></p>
  <% else %>
    <p class="title is-5 has-text-centered mb-3"><%= product.name %></p>
  <% end %>

  <%# card tags %>
  <div class="is-flex is-justify-content-center my-3">
    <% product.categories.each do |c| %>
      <span class="tag is-link is-light is-rounded mx-2"><%= link_to c.name, c %></span>
    <% end %>
  </div>

  <%# product image %>
  <div class="card-image">
    <% if product.image.present? %>
      <%= image_tag product.image %>
    <% end %>
  </div>

  <%# product description %>
  <p class="has-text-justified px-3 py-3"><%= product.description %></p>

  <%# price %>
  <p class="subtitle is-4 my-4 px-3 has-text-centered"><%= number_to_currency product.price.to_i/100.0 %></p>

  <%# buttons %>
    <% if @cart_contents.include?(product) %>
        <%= render partial: "qty_buttons", locals:{ product: product}%>
      <div class="has-text-centered">
          <%= button_to "remove", remove_from_cart_path(product.id), method: :delete, class:"button is-small is-danger is-outlined" %>
      </div>
    <% else %>
      <div class="has-text-centered">
        <%= button_to "add to cart", add_to_cart_path(product.id), method: :post, class:"button is-small"%>
      </div>
    <% end %>

</div>

app/views/products/_qty_buttons.html.erb
<div class="is-flex py-3 is-justify-content-center">
  <%= button_to "-", decrement_from_cart_path(product.id), class:"button is-small is-info is-light is-outlined", method: :delete %>
  <p class="px-3"><%= session[:cart][product.id.to_s]%></p>
  <%= button_to "+", add_to_cart_path(product.id), class:"button is-small is-info is-light is-outlined", method: :post %>
</div>

app/views/products/about.html.erb
<h1 class="title is-2">About Us</h1>

<div class="column is-8">
    <p>Nestled in the southwest corner of charming downtown Canmore, crust & crumb offers a wide selection of baked fresh daily breads and pastries. The bakery features sourdough leavened loaves and a variety of weekly baker's choice specials. crust & crumb partners with local producers to source the freshest and highest quality milled grains, eggs, fruit preserves, and veggies. </p>
</div>

<div id="picbanner" class="column is-7 is-flex is-justify-content-space-between my-5">
    <%= image_tag "pexels-life-of-pix-9095.jpg", size:100 %>
    <%= image_tag "jonathan-pielmayer-j1gr2w10EtQ-unsplash.jpg", size:100 %>
    <%= image_tag "brands-people-yHjcZCaiKFY-unsplash.jpg", size:100 %>
    <%= image_tag "bermix-studio-8tQ7rBFgPu8-unsplash.jpg", size:100 %>
    <%= image_tag "mae-mu-Emhz3miT6mo-unsplash.jpg", size:100 %>
</div>

<div class="is-flex">
    <div class="content mx-6">
        <h4 class="title is-5">mainstay loaves</h4>
        <ul>
            <li>rustic sourdough</li>
            <li>flax & pepitas</li>
            <li>jalepe&ntilde;o cheddar</li>
            <li>cracked rye</li>
            <li>multigrain</li>
        </ul>
    </div>

    <div class="content mx-6">
        <h4 class="title is-5">weekly specials</h4>
        <ul>
            <li>loaf</li>
            <li>cookie</li>
            <!-- <li>loaf</li> -->
            <li>hand pie</li>
            <li>gallette</li>
            <li>baker's choice</li>
        </ul>
    </div>
</div>

app/views/products/edit.html.erb
<h1 class="title">Edit Product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Show this product", @product %> |
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/index.html.erb
<p style="color: green"><%= notice %></p>

<h1 class="title has-text-centered">Products</h1>


<div class="is-flex is-flex-direction-column is-align-items-center">
  <%# display cart contents %>
  <%= render "cart_contents", show_taxes: false %>

  <%# display checkout button %>
  <div class="block is-flex">
    <% unless @cart_contents.empty?%>
      <% if session[:customer_id].nil? %>
        <%= link_to "Checkout", show_login_form_path, class:"button mr-4 is-success is-light is-outlined" %></p>
      <% else %>
        <%= link_to "Checkout", checkout_path, class:"button mr-4 is-success is-light is-outlined" %></p>
      <% end %>
      <%= link_to "Clear Cart", clear_cart_path, class:"button is-danger is-light is-outlined" %></p>
    <% end %>
  </div>
</div>

<%# display products %>
<%#= link_to "New product", new_product_path, class:"button" %>
<div class="columns is-multiline my-5 is-justify-content-center" id="products">
  <% @products.each do |product| %>
    <%# render product %>
    <%= render partial: 'product',
          locals: {show_page: false, product: product} %>
  <% end %>
</div>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.erb
<p style="color: green"><%= notice %></p>

<%# render @product %>
<%= render partial: 'product',
    locals: {show_page: true, product: @product} %>

<div>
  <%#= link_to "Edit this product", edit_product_path(@product) %>
  <%#= link_to "Back to products", products_path %>
  <%#= button_to "Destroy this product", @product, method: :delete %>
</div>

app/views/products/specials.html.erb
<div class="specials is-flex is-flex-direction-column is-align-items-center is-justify-content-center">

  <div class="row">
      <h1 class="title mb-5">Weekly Specials</h1>
  </div>

  <div class="row my-4">
      <div class="weekly is-flex is-justify-content-center is-align-items-center">
          <h2 class="is-flex is-justify-content-end pr-3">loaf</h2>
          <%= image_tag "products/leiliane-fagundes-0sTX2h8FpXk-unsplash.jpg", size:"150" %>
          <%# <img class="special" src="assets/images/products/leiliane-fagundes-0sTX2h8FpXk-unsplash.jpg" alt="chocolate cherry hazelnut loaf"> %>
          <div class="weeklyRow column pl-3">
              <h3>chocolate cherry hazelnut</h3>
              <p style="max-width: 380px;">Cozy up to this dense loaf with decadent chocolate chunks and the nutty crunch of toasted hazelnuts. Enjoy toasted with a pat of melted butter.</p>
          </div>
      </div>
  </div>

  <div class="row my-4">
      <div class="weekly is-flex is-justify-content-center is-align-items-center">
          <h2 class="is-flex is-justify-content-end pr-3">cookie</h2>
          <%= image_tag "products/biscuits-g8f2a0c828_640.jpg", size:"150" %>
          <%# <img class="special" src="assets/images/products/biscuits-g8f2a0c828_640.jpg" alt="lemon crinkle cookie"> %>
          <div class="weeklyRow column pl-3">
              <h3>lemon crinkle</h3>
              <p style="max-width: 380px;">A soft chewy center zippy with lemon tang hides beneath the crackly, sugar dusted crust.</p>
          </div>
      </div>
  </div>


  <div class="row my-4">
      <div class="weekly is-flex is-justify-content-center is-align-items-center">
          <h2 class="is-flex is-justify-content-end pr-3">hand pie</h2>
          <%= image_tag "products/Blackberry-Hand-Pies-8.jpg", size:"150" %>
          <%# <img class="special" src="assets/images/products/Blackberry-Hand-Pies-8.jpg" alt="blackberry hand pie"> %>
          <div class="weeklyRow column pl-3">
              <h3>blackberry</h3>
              <p style="max-width: 380px;">The pop tart of your dreams. This week's hand pie is bursting with blackberry preserves and drizzled with blackberry icing.</p>
          </div>
      </div>
  </div>


  <div class="row my-4">
      <div class="weekly is-flex is-justify-content-center is-align-items-center">
          <h2 class="is-flex is-justify-content-end pr-3">galette</h2>
          <%= image_tag "products/jane-yokata-ZNtT8W11HFQ-unsplashcrop.jpg", size:"150" %>
          <%# <img class="special" src="assets/images/products/jane-yokata-ZNtT8W11HFQ-unsplashcrop.jpg" alt="blueberry peach galette"> %>
          <div class="weeklyRow column pl-3">
              <h3>blueberry peach</h3>
              <p style="max-width: 380px;">Preserved peaches and blueberries from last summer's harvest will have you dreaming of a fragrant summer breeze.</p>
          </div>
      </div>
  </div>

  <div class="row my-4">
      <div class="weekly is-flex is-justify-content-center is-align-items-center">
          <h2 class="is-flex is-justify-content-end pr-3">baker's choice</h2>
          <%= image_tag "products/lecoquin-foods-74u78crHyeI-unsplashcrop.jpg", size:"150" %>
          <%# <img class="special" src="assets/images/products/lecoquin-foods-74u78crHyeI-unsplashcrop.jpg" alt="parm spinach spiral"> %>
          <div class="weeklyRow column pl-3">
              <h3>parm spinach spiral</h3>
              <p style="max-width: 380px;">Tender spinach is punctuated with sharp cheesy notes of parmigiano reggiano in this savoury pastry.</p>
          </div>
      </div>
  </div>
</div>