config/routes.rb
Rails.application.routes.draw do
  root "products#index"
  resources :customers
  resources :provinces
  resources :categories
  resources :products
  resources :orders
  resources :product_categories
  resources :order_products

  post    'add_to_cart/:id',          to: "products#add_to_cart",         as: "add_to_cart"
  delete  'remove_from_cart/:id',     to: "products#remove_from_cart",    as: "remove_from_cart"
  delete  'decrement_from_cart/:id',  to: "products#decrement_from_cart", as: "decrement_from_cart"
  get     'clear_cart',               to: "products#clear_cart",          as: "clear_cart"

  get     "login",  to: "customers#login",        as: "show_login_form"
  post    "login",  to: "customers#authenticate", as:"authenticate"
  delete  "logout", to: "customers#logout",       as:"logout"

  get "checkout", to: "checkout#index", as: "checkout"
  get "thankyou", to: "checkout#thankyou"

  get "invoice", to: "orders#invoice", as: "invoice"

  get "about", to: "products#about", as: "about"
  get "specials", to: "products#specials", as: "specials"

end


  # GET	      /photos	          photos#index	  display a list of all photos
  # POST	    /photos	          photos#create	  create a new photo
  # GET	      /photos/new	      photos#new	    return an HTML form for creating a new photo
  # GET	      /photos/:id	      photos#show	    display a specific photo
  # PATCH/PUT	/photos/:id	      photos#update	  update a specific photo
  # DELETE	  /photos/:id	      photos#destroy	delete a specific photo
  # GET	      /photos/:id/edit	photos#edit	    return an HTML form for editing a photo

  # photos_path           returns /photos
  # new_photo_path        returns /photos/new
  # edit_photo_path(:id)  returns /photos/:id/edit (edit_photo_path(10) returns /photos/10/edit)
  # photo_path(:id)       returns /photos/:id (photo_path(10) returns /photos/10)

app/views/layouts/_footer.html.erb
<footer class="footer py-4" style="background-color: #3a353b">
  <div class="is-flex is-justify-content-center" id="address">
    <p class="is-size-5 is-size-6-mobile px-3">850 8th St</p>
    <p class="is-size-5 is-size-6-mobile px-3">Canmore, Alberta</p>
    <p class="is-size-5 is-size-6-mobile px-3">T2W 5B4</p>
    <p class="is-size-5 is-size-6-mobile px-3">CANADA</p>
  </div>
  <div class="is-flex is-justify-content-center" id="devBy">
    <p class="is-size-6 px-2 py-3">Website Design & Development</p>
    <p class="is-size-6 px-2 py-3 has-text-weight-bold">&bull;</p>
    <p class="is-size-6 px-2 py-3">Marissa Steindel</p>
    <p class="is-size-6 px-2 py-3 has-text-weight-bold">&bull;</p>
    <p class="is-size-6 px-2 py-3">2023</p>
  </div>
</footer>

app/views/layouts/_menu.html.erb
<div id="hero">
  <a href="<%= root_path %>">
    <p>crust <span>&</span> crumb</p>
  </a>
</div>

<%# <p>session[:cart]:  <%= session[:cart].inspect ></p> %>
<%# <p>session[:customer_id]:  <%= session[:customer_id].inspect ></p> %>

<nav class="navbar is-primary" id="main-navbar">
  <%= link_to "Home", root_path, :class=>"navbar-item" %>
  <%= link_to "About", about_path, :class=>"navbar-item" %>
  <%= link_to "Specials", specials_path, :class=>"navbar-item" %>
  <%# link_to "Contact Us", contact_path, :class=>"navbar-item" %>
  <%# link_to "Admin", admin_root_path, :class=>"navbar-item" %>

  <%# display number of items in cart %>
  <% unless session[:cart].empty? %>
    <%= link_to "Checkout [#{session[:cart].values.sum}]", checkout_path, :class=>"navbar-item" %>
  <% end %>

  <%# Display customer, if signed in %>
  <% unless session[:customer_id].nil? %>
    <p class="navbar-item ml-6 mr-2"><%= "Welcome, #{Customer.find_by(id: session[:customer_id]).name.capitalize}"%></p>
    <%= button_to "Log Out", logout_path, method: :delete, :class=>" navbar-item button is-small mt-3" %>
  <% else %>
    <%= link_to "Login", show_login_form_path, :class=>"navbar-item" %>
    <%= link_to "Sign Up", new_customer_path, :class=>"navbar-item" %>
  <% end %>

</nav>

<nav class="navbar is-warning" id="models-navbar">
    <%= link_to "Products Collection", products_path, :class=>"navbar-item" %>
    <%= link_to "Categories Collection", categories_path, :class=>"navbar-item" %>
    <%= link_to "Provinces Collection", provinces_path, :class=>"navbar-item" %>
    <%= link_to "Customers Collection", customers_path, :class=>"navbar-item" %>
    <%= link_to "Orders Collection", orders_path, :class=>"navbar-item" %>
    <div class="navbar-item has-dropdown is-hoverable">
      <a class="navbar-link">JoinTables</a>
      <div class="navbar-dropdown">
        <%= link_to "ProductCategories", product_categories_path, :class=>"navbar-item" %>
        <%= link_to "OrderProducts", order_products_path, :class=>"navbar-item" %>
      </div>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crust & Crumb Bakery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
  </head>

  <body>
    <%= render "layouts/menu" %>
    <div class="section is-flex is-flex-direction-column is-align-items-center">
      <%= yield %>
    </div>
    <%= render "layouts/footer" %>
  </body>
</html>